/**
 * Writes sample-data/messy/, a deliberately broken copy of one month.
 *
 * It exists so the ingest and the empty states can be demonstrated rather than
 * described: upload these three files and every gap the dashboard knows how to
 * surface appears at once.
 *
 *   npm run make:messy
 */
import { mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import ExcelJS from 'exceljs';

const OUT_DIR = join(process.cwd(), 'sample-data', 'messy');

async function timesheet(): Promise<ExcelJS.Workbook> {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Sheet1');

  // Two rows of preamble, so the header is not in row 1.
  sheet.addRow(['Tentwenty — monthly timesheet export']);
  sheet.addRow(['generated by finance, do not edit']);
  sheet.addRow([]);
  sheet.addRow([
    'Month',
    'Employee No.',
    'Employee Name',
    'Type of Expense',
    'Department',
    'Designation',
    'Category',
    'Ref Code',
    'Project (Billable) / Task (Unbillable) Name',
    'Company Name (Billable)/ Fixed Costs (Unbillable)',
    'Description',
    'Hours',
  ]);

  const rows: (string | number)[][] = [
    // Three spellings of the same month, all of which must resolve to March 2025.
    ["March '25", '10201', 'Ayesha Rahman', 'DL', 'Design', 'Senior UI/UX Designer', 'Projects', 'Q2025001a', 'Meridian website', 'Meridian Group', 'design', 120],
    ['March 2025', '10202', 'Rohit Menon', 'DL', 'Design', 'UI/UX Designer', 'Projects', 'Q2025001a', 'Meridian website', 'Meridian Group', 'build', 96.5],
    ['Mar-25', '10203', 'Lina Haddad', 'DL', 'Design', 'Team Lead - Design', 'FC - Meetings', 'FC - Meetings', 'Internal', 'Fixed Costs', 'internal', 30],
    // No year at all: the loader infers it from the rest of the file.
    ['March', '10203', 'Lina Haddad', 'DL', 'Design', 'Team Lead - Design', 'Projects', 'Q2025001a', 'Meridian website', 'Meridian Group', 'review', 80],
    // A ref code that is not in the price sheet.
    ['March 2025', '10204', 'Tariq Aziz', 'DL', 'Frontend', 'Senior Frontend Developer', 'Projects', 'Q2025099z', 'Unlisted side project', 'Someone', 'build', 64],
    // Someone with hours but no salary row anywhere.
    ['March 2025', '10999', 'Ghost Contractor', 'DL', 'Frontend', 'Contractor', 'Projects', 'Q2025001a', 'Meridian website', 'Meridian Group', 'overflow', 40],
    // Blanks written as a dash, which must not become zero-cost noise.
    ['March 2025', '10205', 'Grace Fernandes', 'DL', 'Frontend', 'Frontend Developer', 'FC - Leaves', 'FC - Leaves', 'Leave', 'Fixed Costs', '-', '-'],
    // No category: counted as Uncategorised rather than dropped.
    ['March 2025', '10205', 'Grace Fernandes', 'DL', 'Frontend', 'Frontend Developer', '-', '-', 'Unknown', 'Fixed Costs', '?', 12],
    // No employee name: skipped, with the row number reported.
    ['March 2025', '-', '-', 'DL', '-', '-', 'Projects', 'Q2025001a', '-', '-', '-', 8],
    // An unreadable month: skipped, with the row number reported.
    ['Q1', '10206', 'Imran Sheikh', 'DL', 'Backend', 'Senior Backend Developer', 'Projects', 'Q2025001a', 'Meridian website', 'Meridian Group', 'api', 20],
    // A trailing total row, which carries no employee and is ignored.
    ['Total', '', '', '', '', '', '', '', '', '', '', 470.5],
  ];

  for (const row of rows) sheet.addRow(row);
  return workbook;
}

async function salaries(): Promise<ExcelJS.Workbook> {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Salary');

  // Title in row 1 carrying the year, header in row 2.
  sheet.addRow([null, 'Salary Overview 2025 (AED)']);
  sheet.addRow(['Employee No.', 'Employee Name', 'January', 'February', 'March']);
  sheet.addRow(['10201', 'Ayesha Rahman', 18000, 18000, 18000]);
  sheet.addRow(['10202', 'Rohit Menon', 12000, 12000, '12,500']);
  sheet.addRow(['10203', 'Lina Haddad', 22000, '-', 22000]);
  sheet.addRow(['10204', 'Tariq Aziz', 17000, 17000, 17000]);
  sheet.addRow(['10205', 'Grace Fernandes', 11000, 11000, 11000]);
  sheet.addRow(['10206', 'Imran Sheikh', 19000, 19000, 19000]);
  // Paid, but logged nothing in March: the whole salary lands in the pool.
  sheet.addRow(['00101', 'Hana Yousef', 20000, 20000, 20000]);

  return workbook;
}

async function projects(): Promise<ExcelJS.Workbook> {
  const workbook = new ExcelJS.Workbook();
  const sheet = workbook.addWorksheet('Projects');

  sheet.addRow(['Ref Code', 'Project (Billable) Name', 'Project Price', 'Sales month', 'Category', 'Status']);
  sheet.addRow(['Q2025001a', 'Meridian website', 560000, "January '25", 'Projects', 'in progress']);
  // A price written as a dash: the project loads, its margin does not.
  sheet.addRow(['Q2025004c', 'Alwasl app', '-', 'February 2025', 'Projects', 'in progress']);
  // Sold, but nobody logged an hour against it.
  sheet.addRow(['Q2025088x', 'Never started', 75000, 'Mar-25', 'Projects', 'in progress']);
  // A duplicate ref code: the later row wins, and the collision is reported.
  sheet.addRow(['Q2025001a', 'Meridian website (restated)', 575000, "January '25", 'Projects', 'in progress']);

  return workbook;
}

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });

  const files: [string, ExcelJS.Workbook][] = [
    ['timesheet-messy.xlsx', await timesheet()],
    ['salaries-messy.xlsx', await salaries()],
    ['project-prices-messy.xlsx', await projects()],
  ];

  for (const [name, workbook] of files) {
    await workbook.xlsx.writeFile(join(OUT_DIR, name));
    console.log(`wrote sample-data/messy/${name}`);
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
